copyright = "CC BY 4.0"
defaultContentLanguage = "en-us"
baseURL = "https://wwww.thiagohenrique.com.br/"

pygmentsCodeFences = true

theme = "hugo-kiera"

[languages]

  [languages.en-us]
    weight = 1
    title = "Another nerdy blog"

  [languages.pt-br]
    weight = 2
    title = "Outro blog nerd"

[params]
  tagline = "No bike-shed effect"

[author]
  name          = "Thiago Henrique"
  devto         = "thiagohdeplima"
  github        = "thiagohdeplima"
  linkedin      = "thenrique"
  twitter       = "thiagohdeplima"
  instagram     = "thiagohdeplima"
  stackoverflow = "users/5036456/thiago-henrique"